name: Executar bot a cada 1 hora

on:
  schedule:
    - cron: '0 * * * *'  # A cada 1 hora
  workflow_dispatch:

jobs:
  rodar-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar bot
        run: python main.py
